Tesla Booking
Draxeytina/Back-end_Tesla-Booking pull request #31
Opened 2022-11-01 21:46 UTC by waqaskanju

This is pull  we completed our final capstone with the following requirements:

- The user can register and login.
- This project is for booking Tesla cars.
- There is "Reserve  form. for car reservation
- One can see his reservations.
- Cars can be added and deleted by the admin user.
- on the main page we can see list of cars
-  On selecting a car one can see its details.
- - Its responsive for both mobile and desktop screen.

The front it is created in using React-Redux which is using Rails api
Link to the frontend repo [Front end Repo Link](https://github.com/Draxeytina/Front-end_Tesla-Booking)

Some Pictures of the Project.

2022-11-01 23:01 UTC, Meltrust requested changes
Hi @waqaskanju,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  API is working ✔️ 
-  Good readme ✔️ 
-  Nice auth ✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Suggested Changes ♻️
_Check the comments under the review._

You can use as many of my suggestions as you want.  If there is anything you would like to skip - feel free to do that.  However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2022-11-01 23:01 UTC, Meltrust commented on README.md
> +
- [ ] On the "license" section, the link is broken because it is pointing to a file does not exist.  Please, kindly go [here](https://github.com/microverseinc/readme-template) and grab the `MIT.md` file, copy it to the root of your project, and link to it on your readme's license section.

That way, your app will be well documented 💪

2022-11-01 23:01 UTC, Meltrust commented on README.md
> +
- [ ] In the instructions about how to run your project, kindly add the db initialization commands that your users will need to run your app:

```bash
rails db:create
rails db:migrate
rails db:seed
```

That way, your users will be able to run your app smoothly 👍

2022-11-01 23:01 UTC, Meltrust commented on README.md
> +
- [ ] Your Rails API has no tests.  Kindly add at least some tests to ensure your app's integrity. Please, remember also to include instructions about how to run the tests on your readme.

In the industry, we write tests every day for each feature implemented.  You will need this skill for your next brand-new job 💪

2022-11-01 23:19 UTC, Gopxfs commented on README.md
> +
Hello @Meltrust, thanks for the advice, we will implement the testings!

2022-11-02 04:25 UTC, Meltrust approved these changes
#### Hi @waqaskanju,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- The API works well✔️ 
- Screenshot has been implemented✔️ 
- Tests have been implemented✔️
- Readme file has been corrected ✔️  
- The auth has quality ✔️ 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

You can use as many of my suggestions as you want.  If there is anything you would like to skip - feel free to do that.  However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏


------

2022-11-02 19:16 UTC, merged